In [6]:
from __future__ import print_function, division

%matplotlib inline

import numpy as np
import pandas as pd

import AAPL

In [11]:
aapl_df = AAPL.ReadAAPL()

In [13]:
aapl_df

,0,1,2,3,4,5,6
0,Date,Open,High,Low,Close,Adj Close,Volume
1,2000-11-27,1.419643,1.424107,1.321429,1.334821,0.893880,64698200
2,2000-11-28,1.334821,1.357143,1.281250,1.287943,0.862488,67281200
3,2000-11-29,1.292407,1.308036,1.232143,1.254464,0.840068,123037600
4,2000-11-30,1.191964,1.214286,1.151786,1.178571,0.789246,202399400
5,2000-12-01,1.214286,1.250000,1.200893,1.218750,0.816152,96426400
6,2000-12-04,1.227679,1.227679,1.174107,1.191964,0.798214,92880200
7,2000-12-05,1.209821,1.245536,1.169643,1.214286,0.813162,153494600
8,2000-12-06,1.044643,1.071429,1.000000,1.022321,0.684611,343616000
9,2000-12-07,1.031250,1.062500,1.000000,1.022321,0.684611,102229400
10,2000-12-08,1.058036,1.093750,1.031250,1.075893,0.720485,108906000
11,2000-12-11,1.084821,1.098214,1.062500,1.084821,0.726465,83127800
12,2000-12-12,1.089286,1.142857,1.071429,1.098214,0.735433,96565000
13,2000-12-13,1.111607,1.111607,1.062500,1.071429,0.717496,86221800
14,2000-12-14,1.073657,1.089286,1.031250,1.031250,0.690590,65829400
15,2000-12-15,1.040179,1.049107,1.000000,1.004464,0.672652,128486400
16,2000-12-18,1.040179,1.044643,0.995536,1.017857,0.681621,81452000
17,2000-12-19,1.026786,1.089286,1.000000,1.000000,0.669663,93501800
18,2000-12-20,0.984371,1.044643,0.973214,1.026786,0.687600,141332800
19,2000-12-21,1.017857,1.071429,0.991071,1.004464,0.672652,91711200
20,2000-12-22,1.008929,1.071429,1.008929,1.071429,0.717496,79513000
21,2000-12-26,1.062500,1.071429,1.017857,1.049107,0.702548,54203800
22,2000-12-27,1.024550,1.058036,1.013393,1.058036,0.708527,81366600
23,2000-12-28,1.026786,1.066964,1.022321,1.058036,0.708527,76294400
24,2000-12-29,1.049107,1.071429,1.035714,1.062500,0.711517,157584000
25,2001-01-02,1.062500,1.089286,1.040179,1.062500,0.711517,113078000
26,2001-01-03,1.035714,1.191964,1.031250,1.169643,0.783266,204268400
27,2001-01-04,1.295757,1.321429,1.200893,1.218750,0.816152,184849000
28,2001-01-05,1.209821,1.241071,1.147321,1.169643,0.783266,103089000
29,2001-01-08,1.209821,1.213164,1.138393,1.183036,0.792235,93424800
...,...,...,...,...,...,...,...
4500,2018-10-16,218.929993,222.990005,216.759995,222.149994,221.377563,29184000
4501,2018-10-17,222.300003,222.639999,219.339996,221.190002,220.420914,22885400
4502,2018-10-18,217.860001,219.740005,213.000000,216.020004,215.268890,32581300
4503,2018-10-19,218.059998,221.259995,217.429993,219.309998,218.547455,33078700
4504,2018-10-22,219.789993,223.360001,218.940002,220.649994,219.882782,28792100
4505,2018-10-23,215.830002,223.250000,214.699997,222.729996,221.955551,38767800
4506,2018-10-24,222.600006,224.229996,214.539993,215.089996,214.342117,40925500
4507,2018-10-25,217.710007,221.380005,216.750000,219.800003,219.035751,29855800
4508,2018-10-26,215.899994,220.190002,212.669998,216.300003,215.547913,47258400
4509,2018-10-29,219.190002,219.690002,206.089996,212.240005,211.502045,45935500
4510,2018-10-30,211.149994,215.179993,209.270004,213.300003,212.558350,36660000
4511,2018-10-31,216.880005,220.449997,216.619995,218.860001,218.099014,38358900
4512,2018-11-01,219.050003,222.360001,216.809998,222.220001,221.447327,58323200
4513,2018-11-02,209.550003,213.649994,205.429993,207.479996,206.758575,91328700
4514,2018-11-05,204.300003,204.389999,198.169998,201.589996,200.889053,66163700
4515,2018-11-06,201.919998,204.720001,201.690002,203.770004,203.061493,31882900
4516,2018-11-07,205.970001,210.059998,204.130005,209.949997,209.219986,33424400
4517,2018-11-08,209.979996,210.119995,206.750000,208.490005,208.490005,25362600
4518,2018-11-09,205.550003,206.009995,202.250000,204.470001,204.470001,34365800
4519,2018-11-12,199.000000,199.850006,193.789993,194.169998,194.169998,51135500
4520,2018-11-13,191.630005,197.179993,191.449997,192.229996,192.229996,46882900
4521,2018-11-14,193.899994,194.479996,185.929993,186.800003,186.800003,60801000
4522,2018-11-15,188.389999,191.970001,186.899994,191.410004,191.410004,46478800
4523,2018-11-16,190.500000,194.970001,189.460007,193.529999,193.529999,36928300
4524,2018-11-19,190.000000,190.699997,184.990005,185.860001,185.860001,41925300
4525,2018-11-20,178.369995,181.470001,175.509995,176.979996,176.979996,67825200
4526,2018-11-21,179.729996,180.270004,176.550003,176.779999,176.779999,31124200
4527,2018-11-23,174.940002,176.600006,172.100006,172.289993,172.289993,23624000
4528,2018-11-26,174.240005,174.949997,170.259995,174.619995,174.619995,44998500
4529,2018-11-27,171.509995,174.770004,170.880005,174.240005,174.240005,41256200